<<<<<<< HEAD
=======
# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

>>>>>>> ed35298cfcb8ffaf36cd80a11e287f89de945b5c
name: Node.js CI

on:
  push:
<<<<<<< HEAD
    branches: ["main"]

jobs:
  build:
=======
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

>>>>>>> ed35298cfcb8ffaf36cd80a11e287f89de945b5c
    runs-on: ubuntu-latest

    strategy:
      matrix:
<<<<<<< HEAD
        node-version: [18.x]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Backend Dependencies
        run: |
          cd Backend
          npm install

      - name: Check Backend
        run: |
          cd Backend
          npm run dev
=======
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
>>>>>>> ed35298cfcb8ffaf36cd80a11e287f89de945b5c
